unpackaged/main/default/objects/Product2/fields/Analyses_realisees__c.field-meta.xml
<CustomField>
    <fullName>Analyses_realisees__c</fullName>
    <description>2PACE</description>
    <label>Analyse(s) réalisée(s)</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Conseil__c.field-meta.xml
<CustomField>
    <fullName>Conseil__c</fullName>
    <description>2PACE</description>
    <label>Conseil</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Delai__c.field-meta.xml
<CustomField>
    <fullName>Delai__c</fullName>
    <description>2PACE</description>
    <label>Délai</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Espece__c.field-meta.xml
<CustomField>
    <fullName>Espece__c</fullName>
    <description>2PACE</description>
    <label>Espèce</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chien,CHIEN</fullName>
                <label>Chien</label>
            </value>
            <value>
                <fullName>Chat,CHAT</fullName>
                <label>Chat</label>
            </value>
            <value>
                <fullName>Cheval,CHEV</fullName>
                <label>Cheval</label>
            </value>
            <value>
                <fullName>Lagomorphe,LAGOM</fullName>
                <label>Lagomorphe</label>
            </value>
            <value>
                <fullName>Oiseaux,OISE</fullName>
                <label>Oiseaux</label>
            </value>
            <value>
                <fullName>Cobaye,COB</fullName>
                <label>Cobaye</label>
            </value>
            <value>
                <fullName>Furet,FURET</fullName>
                <label>Furet</label>
            </value>
            <value>
                <fullName>Reptile,REPT</fullName>
                <label>Reptile</label>
            </value>
            <value>
                <fullName>Rat,RAT</fullName>
                <label>Rat</label>
            </value>
            <value>
                <fullName>Souris,SO</fullName>
                <label>Souris</label>
            </value>
            <value>
                <fullName>Ane,ANE</fullName>
                <label>Ane</label>
            </value>
            <value>
                <fullName>Bovin,BOVIN</fullName>
                <label>Bovin</label>
            </value>
            <value>
                <fullName>Caprin,CAPRI</fullName>
                <label>Caprin</label>
            </value>
            <value>
                <fullName>Ovin,OVIDE</fullName>
                <label>Ovin</label>
            </value>
            <value>
                <fullName>Porc,POR</fullName>
                <label>Porc</label>
            </value>
            <value>
                <fullName>Autres,AUTRE</fullName>
                <label>Autres</label>
            </value>
            <value>
                <fullName>A définir</fullName>
                <isActive>false</isActive>
                <label>- A définir</label>
            </value>
            <value>
                <fullName>Dauphin</fullName>
                <isActive>false</isActive>
                <label>Dauphin</label>
            </value>
            <value>
                <fullName>Rongeur</fullName>
                <isActive>false</isActive>
                <label>Rongeur</label>
            </value>
            <value>
                <fullName>Toutes</fullName>
                <isActive>false</isActive>
                <label>Toutes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Favorite__c.field-meta.xml
<CustomField>
    <fullName>Favorite__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Champ pour mettre en avant le produit dans OCO</inlineHelpText>
    <label>Favori</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/infos__c.field-meta.xml
<CustomField>
    <fullName>infos__c</fullName>
    <description>2PACE</description>
    <label>infos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/New__c.field-meta.xml
<CustomField>
    <fullName>New__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Ce champ permet de mettre en avant un examen en tant que nouveau dans l&#39;application OCO (Ordonnance Connectée).</description>
    <inlineHelpText>Ce champ permet de mettre en avant un examen en tant que nouveau dans l&#39;application OCO (Ordonnance Connectée).</inlineHelpText>
    <label>Nouveauté</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/oco_custom_field_label__c.field-meta.xml
<CustomField>
    <fullName>oco_custom_field_label__c</fullName>
    <description>Label permettant à OCO d&#39;afficher un champ personnalisé. Si rempli, cocher oco_custom_field_visible</description>
    <inlineHelpText>Label permettant à OCO d&#39;afficher un champ personnalisé. Si rempli, cocher oco_custom_field_visible</inlineHelpText>
    <label>oco_custom_field_label</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/oco_custom_field_visible__c.field-meta.xml
<CustomField>
    <fullName>oco_custom_field_visible__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicateur permettant à OCO d&#39;afficher un champ personnaliser. Si coché, remplir oco_custom_field_label</description>
    <inlineHelpText>Indicateur permettant à OCO d&#39;afficher un champ personnaliser. Si coché, remplir oco_custom_field_label</inlineHelpText>
    <label>oco_custom_field_visible</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Preanalytique__c.field-meta.xml
<CustomField>
    <fullName>Preanalytique__c</fullName>
    <description>2PACE</description>
    <inlineHelpText>Nomenclature :  Matrice ; Contenant/tube ; Température de Transport</inlineHelpText>
    <label>Pré-analytique</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Prix_Degressif__c.field-meta.xml
<CustomField>
    <fullName>Prix_Degressif__c</fullName>
    <defaultValue>false</defaultValue>
    <description>TRUE if the product has a diminishing pricing.</description>
    <label>Prix Dégressif</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Qte_souhaitee__c.field-meta.xml
<CustomField>
    <fullName>Qte_souhaitee__c</fullName>
    <description>2PACE</description>
    <label>Qte souhaitée</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/SubContracting__c.field-meta.xml
<CustomField>
    <fullName>SubContracting__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Ce champ permet de mettre en avant dans l&#39;application OCO (Ordonnance Connectée) si l&#39;examen requiert une sous traitance.</description>
    <inlineHelpText>Ce champ permet de mettre en avant dans l&#39;application OCO (Ordonnance Connectée) si l&#39;examen requiert une sous traitance.</inlineHelpText>
    <label>Analyse Sous-traitée</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Visible_Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Visible_Catalogue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>2PACE</description>
    <inlineHelpText>Produit Présent sur FDE et Site web</inlineHelpText>
    <label>Visible Catalogue</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/OcoExamsApi.cls
@RestResource(urlMapping='/oco/exams')
global with sharing class OcoExamsApi {
    
    global class Market {
        public String Name { get; set; }
    }
   
    global class Specie {
        public String Name { get; set; }
        public String HexalisCode { get; set; }
    }
    
    global class Exam {
        
        /** Main informations **/
        public String Id { get; set; }
        public String Code { get; set; }
        public String Name { get; set; }
        public String Family { get; set; }
        public Specie[] Species { get; set; }
        public String Preanalytics { get; set; }
        public Boolean Favorite { get; set; }
        public Boolean NewExam { get; set; }
        // public Market[] Market { get; set; }
        public Boolean SubContracting { get; set; }
        public String RealizedAnalyses { get; set; }
        public String Description { get; set; }
        
        /** Detail informations **/
        public String Advices { get; set; }
        public String AdditionalInformations  { get; set; }
        public String SamplesQuantities  { get; set; }
        public String ProcessingDelay  { get; set; }
        public Boolean DegressivePrice { get; set; }
        public Double DegressivePriceAmount { get; set; }
        
        /* Custom field */
        public Boolean CustomFieldVisible { get; set; }
        public String CustomFieldLabel { get; set; }
    }
    
    // Method to convert species from multipick list string to List<Specie>
    public static List<Specie> getSpeciesList(String species)
    {
        // The str string is formatted like this "name;name;name;"
        List<Specie> speciesList = new List<Specie>();
        
        // Empty species handling
        if (species == null || species == '')
        {
	        return speciesList;
        }
        
        // Get a String list of species and loop through it
        List<String> stringList = species.split(';');
        for (Integer index = 0; index < stringList.size(); index++) 
        {
            // Add the specie to the speciesList if valid
            if (stringList[index] != null && stringList[index] != '')
            {
                // Split string to get 'specie,code'
                List<String> splittedString = stringList[index].split(',');
                
                // Error handling
                if (splittedString.size() > 0) {
                    Specie specie = new Specie();
                    specie.Name = splittedString[0]; 
                    specie.HexalisCode = (splittedString.size() > 1) ? splittedString[1] : ''; 
                    speciesList.add(specie);                
                }
            }
        }
        
        // Return created speciesList
        return speciesList;
    }
    
    // Endpoint to get all exams data
    @HttpGet
    global static List<Exam> getExams() {       
        // Get exams from Salesforce table
        List<Product2> result = [SELECT Id, ProductCode, Name, Family, Espece__c, Preanalytique__c,  
                                 Favorite__c, New__c, SubContracting__c, Analyses_realisees__c, Description, 
                                 Conseil__c, infos__c, Qte_souhaitee__c, Delai__c, Prix_degressif__c,
                                 oco_custom_field_visible__c, oco_custom_field_label__c
                                 FROM Product2 
                                 WHERE IsActive = true
                                 AND Visible_Catalogue__c = true];
        
        // Create custom exam object list
        List<Exam> examList = new List<Exam>();
        
        // Fill list with Salesforce data
        for (Integer index = 0; index < result.size(); index++) {
            // Create custom exam model
	        Exam exam = new Exam();
            
            // Main informations
			exam.Id = result[index].Id;
			exam.Code = result[index].ProductCode;
			exam.Name = result[index].Name;
			exam.Family = result[index].Family;
            exam.Species = getSpeciesList(result[index].Espece__c);
            exam.Preanalytics = result[index].Preanalytique__c;
			exam.Favorite = result[index].Favorite__c;
            exam.NewExam = result[index].New__c;
            // TODO: Market
			exam.SubContracting = result[index].SubContracting__c;
			exam.RealizedAnalyses = result[index].Analyses_realisees__c;  
			exam.Description = result[index].Description;  
            
            // Detais informations
			exam.Advices = result[index].Conseil__c;  
			exam.AdditionalInformations = result[index].infos__c;  
			exam.SamplesQuantities = result[index].Qte_souhaitee__c;  
			exam.ProcessingDelay = result[index].Delai__c;  
			exam.DegressivePrice = result[index].Prix_Degressif__c;  
            exam.DegressivePriceAmount = 0;
            
            // Custom field
			exam.CustomFieldVisible = result[index].oco_custom_field_visible__c;  
			exam.CustomFieldLabel = result[index].oco_custom_field_label__c;  
            
            // Add exam model to the list
            examList.add(exam);
        }

        // Return the created list
        return examList;
    }
}