unpackaged/main/default/objects/Cout_de_transport__c/Cout_de_transport__c.object-meta.xml
<CustomObject>
    <label>Coût de transport</label>
    <nameField>
        <label>Nom du coût de transport</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coûts de transport</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Mensualite__c/Mensualite__c.object-meta.xml
<CustomObject>
    <label>Mensualité</label>
    <nameField>
        <label>Mensualité</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mensualités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mensualite__c/fields/Cout_de_transport__c.field-meta.xml
<CustomField>
    <fullName>Cout_de_transport__c</fullName>
    <label>Coût de transport</label>
    <referenceTo>Cout_de_transport__c</referenceTo>
    <relationshipLabel>Mensualités</relationshipLabel>
    <relationshipName>mensualites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Mensualite__c/fields/Date_de_la_mensualite__c.field-meta.xml
<CustomField>
    <fullName>Date_de_la_mensualite__c</fullName>
    <label>Date de la mensualité</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Mensualite__c/fields/Montant_provisionne_TTC__c.field-meta.xml
<CustomField>
    <fullName>Montant_provisionne_TTC__c</fullName>
    <label>Montant provisionné TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/MensualiteDao.cls
public inherited sharing class MensualiteDao {

    public static List<Mensualite__c> getMensualitesFromCoutAndDate(Id coutTransportId, Date dateFin){
        return [Select Id, Cout_de_transport__c, Date_de_la_mensualite__c, Montant_provisionne_TTC__c 
                From Mensualite__c 
                Where Cout_de_transport__c = :coutTransportId and Date_de_la_mensualite__c >= :dateFin];
    }
    
    public static List<Mensualite__c> getCurrentMensualite(List<Id> cdtsId){
        return [Select Id, Cout_de_transport__c, Date_de_la_mensualite__c, Montant_provisionne_TTC__c 
                From Mensualite__c 
                Where Cout_de_transport__c in :cdtsId and Date_de_la_mensualite__c >= :system.today() 
                	and Date_de_la_mensualite__c <= :system.today().addYears(1)];
    }
    
}