unpackaged/main/default/objects/Cout_de_transport__c/Cout_de_transport__c.object-meta.xml
<CustomObject>
    <label>Coût de transport</label>
    <nameField>
        <label>Nom du coût de transport</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coûts de transport</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Mensualite__c/Mensualite__c.object-meta.xml
<CustomObject>
    <label>Mensualité</label>
    <nameField>
        <label>Mensualité</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mensualités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mensualite__c/fields/Cout_de_transport__c.field-meta.xml
<CustomField>
    <fullName>Cout_de_transport__c</fullName>
    <label>Coût de transport</label>
    <referenceTo>Cout_de_transport__c</referenceTo>
    <relationshipLabel>Mensualités</relationshipLabel>
    <relationshipName>mensualites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MensualiteBatch.cls
global inherited sharing class MensualiteBatch implements Database.Batchable<sObject>, Database.Stateful {

    private List<Cout_de_transport__c> coutTransportList;
    
    global MensualiteBatch() {
        this.coutTransportList = CoutTransportService.checkCoutForGeneration(CoutTransportDao.getAllCurrentCouts());
    }
    
    global Iterable<sObject> start(Database.BatchableContext bc) {
        System.debug('MensualiteBatch start');
        return this.coutTransportList;
    }

    global void execute(Database.BatchableContext bc, List<Cout_de_transport__c> coutTransportList) {
        List<Mensualite__c> mensualites = new List<Mensualite__c>();
        
        for(Cout_de_transport__c coutTransport : coutTransportList){
    		mensualites.addAll(MensualiteService.generateMensualites(coutTransport));
        }
        
        if(mensualites.size() > 0){
            insert mensualites;
        }
    }

    global void finish(Database.BatchableContext bc) {
        System.debug('MensualiteBatch finish');
    }
    
}