unpackaged/main/default/objects/Cout_de_transport__c/Cout_de_transport__c.object-meta.xml
<CustomObject>
    <label>Coût de transport</label>
    <nameField>
        <label>Nom du coût de transport</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coûts de transport</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cout_de_transport__c/fields/Cout_mensuel_attendu_TTC__c.field-meta.xml
<CustomField>
    <fullName>Cout_mensuel_attendu_TTC__c</fullName>
    <label>Coût mensuel attendu TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Cout_de_transport__c/fields/Date_de_demarrage__c.field-meta.xml
<CustomField>
    <fullName>Date_de_demarrage__c</fullName>
    <inlineHelpText>Merci de renseigner le 1er jour du mois de la mensualité.</inlineHelpText>
    <label>Date de démarrage</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Cout_de_transport__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Demande__c/Demande__c.object-meta.xml
<CustomObject>
    <label>Demande</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>N° de la demande</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demandes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Demande__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Demande__c/fields/Debut_d_application_de_la_modification__c.field-meta.xml
<CustomField>
    <fullName>Debut_d_application_de_la_modification__c</fullName>
    <description>Mois de début d’application de la modification</description>
    <inlineHelpText>Mois de début d’application de la modification</inlineHelpText>
    <label>Début d’application de la modification</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Demande__c/fields/Facture_directe__c.field-meta.xml
<CustomField>
    <fullName>Facture_directe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coût de transport</label>
    <referenceTo>Cout_de_transport__c</referenceTo>
    <relationshipLabel>Demandes</relationshipLabel>
    <relationshipName>Demandes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Mensualite__c/Mensualite__c.object-meta.xml
<CustomObject>
    <label>Mensualité</label>
    <nameField>
        <label>Mensualité</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mensualités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mensualite__c/fields/Cout_de_transport__c.field-meta.xml
<CustomField>
    <fullName>Cout_de_transport__c</fullName>
    <label>Coût de transport</label>
    <referenceTo>Cout_de_transport__c</referenceTo>
    <relationshipLabel>Mensualités</relationshipLabel>
    <relationshipName>mensualites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Mensualite__c/fields/Date_de_la_mensualite__c.field-meta.xml
<CustomField>
    <fullName>Date_de_la_mensualite__c</fullName>
    <label>Date de la mensualité</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Mensualite__c/fields/Montant_provisionne_TTC__c.field-meta.xml
<CustomField>
    <fullName>Montant_provisionne_TTC__c</fullName>
    <label>Montant provisionné TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/MensualiteService.cls
public inherited sharing class MensualiteService {
    
    /**
     * Permet de générer les mensualités d'un cout de transport pour l'année en cours.
     */
    public static List<Mensualite__c> generateMensualites(Cout_de_transport__c coutTransport){

        List<Mensualite__c> mensualites = new List<Mensualite__c>();
        
        // Génération des mensualités pour l'année du début du contrat ou l'année en cours.
        Date startDate = (coutTransport.Date_de_demarrage__c != null && coutTransport.Date_de_demarrage__c.year() == system.today().year()) 
            ? coutTransport.Date_de_demarrage__c : Date.newInstance(system.today().year(),1,1);
        
        List<Date> mensualitesDate = getMonthsUntilEndOfYearOrContract(startDate, coutTransport.Date_de_fin__c);
        for(Date mensualiteDate : mensualitesDate){
            Mensualite__c mensualite = new Mensualite__c();
            mensualite.Cout_de_transport__c = coutTransport.Id;
            mensualite.Date_de_la_mensualite__c = mensualiteDate;
            mensualite.Montant_provisionne_TTC__c = calculateProvision(coutTransport);
            mensualites.add(mensualite);
        }
        
        return mensualites;
    }
    
    /**
     * Permet de générer les mensualités d'un cout de transport pour l'année en cours.
     */
    public static List<Mensualite__c> generateMensualitesTrigger(Cout_de_transport__c coutTransport){
        List<Mensualite__c> mensualites = new List<Mensualite__c>();
        
        // Génération des mensualités pour l'année du début du contrat ou l'année en cours.
        Date startDate = coutTransport.Date_de_demarrage__c;
        if(coutTransport.Date_de_demarrage__c == null){
            startDate = Date.newInstance(system.today().year(), 1,1);
        }
             
        List<Date> mensualitesDate = getMonthsUntilEndOfYearOrContract(startDate, coutTransport.Date_de_fin__c);
        for(Date mensualiteDate : mensualitesDate){
            Mensualite__c mensualite = new Mensualite__c();
            mensualite.Cout_de_transport__c = coutTransport.Id;
            mensualite.Date_de_la_mensualite__c = mensualiteDate;
            mensualite.Montant_provisionne_TTC__c = calculateProvision(coutTransport);
            mensualites.add(mensualite);
        }
        
        return mensualites;
    }
    
    @TestVisible
    private static Date getStartDate(Date dateDemarrage,Date todayDate){
        return (dateDemarrage != null && dateDemarrage.year() < todayDate.year()) 
            ? todayDate.toStartOfMonth()  :dateDemarrage;
    }
    
    
    /**
     * Met a jour le montant des mensualité suite a une demande de modification ou supprime les mensualité suite a une demande de suppression.
     */
    public static void updateOrDeleteFromDemande(List<Demande__c> demandes, Map<Id, Cout_de_transport__c> cdtsById){

       	List<Mensualite__c> mensualiteToUpdate = new List<Mensualite__c>();
        List<Mensualite__c> mensualiteToDelete = new List<Mensualite__c>();
        
        for(Demande__c demande : demandes){
            Cout_de_transport__c coutTransport = cdtsById.get(demande.Facture_directe__c);
            if(demande.RecordTypeId == Schema.SObjectType.Demande__c.getRecordTypeInfosByName()
                                        .get('Demande de modification d\'une facture').getRecordTypeId()){
                List<Mensualite__c> mensualites = MensualiteDAO.getMensualitesFromCoutAndDate(coutTransport.Id, demande.Debut_d_application_de_la_modification__c);
                for(Mensualite__c mensualite : mensualites){
                    mensualite.Montant_provisionne_TTC__c = calculateProvision(coutTransport);
                }
                mensualiteToUpdate.addAll(mensualites);
            } else if(demande.RecordTypeId == Schema.SObjectType.Demande__c.getRecordTypeInfosByName()
                                        .get('Demande de suppression d\'une facture').getRecordTypeId()){
                List<Mensualite__c> mensualites = MensualiteDAO.getMensualitesFromCoutAndDate(coutTransport.Id, demande.Date_de_fin__c);
          
                mensualiteToDelete.addAll(mensualites);
            }
        }
        
        if(mensualiteToUpdate.size() > 0){
            update mensualiteToUpdate;
        }
        if(mensualiteToDelete.size() > 0){
            delete mensualiteToDelete;
        }
    }
    
    public static Decimal calculateProvision(Cout_de_transport__c coutTransport){
            return coutTransport.Cout_mensuel_attendu_TTC__c;     
    }
    
    // ######################################
    
    private static List<Date> getMonthsUntilEndOfYearOrContract(Date startOfCout, Date endOfCout){
        system.debug('MensualiteService.getMonthsUntilEndOfYearOrContract');
        List<Date> mensualitesDate = new List<Date>();
        mensualitesDate.add(startOfCout);
        
        Date startOfMonth = startOfCout.toStartOfMonth().addMonths(1);
        while(endOfCout == null ? startOfMonth.year() <= system.today().year() : startOfMonth < endOfCout){
            mensualitesDate.add(Date.newInstance(startOfMonth.year(), startOfMonth.month(), startOfMonth.day()));
            startOfMonth = startOfMonth.addMonths(1);
        }
        
        system.debug('mensualitesDate (' + mensualitesDate.size() + ') : ' + mensualitesDate);
        return mensualitesDate;
    }
  
}