unpackaged/main/default/objects/Cout_de_transport__c/Cout_de_transport__c.object-meta.xml
<CustomObject>
    <label>Coût de transport</label>
    <nameField>
        <label>Nom du coût de transport</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coûts de transport</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cout_de_transport__c/fields/Cout_mensuel_attendu_TTC__c.field-meta.xml
<CustomField>
    <fullName>Cout_mensuel_attendu_TTC__c</fullName>
    <label>Coût mensuel attendu TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Cout_de_transport__c/fields/Date_de_demarrage__c.field-meta.xml
<CustomField>
    <fullName>Date_de_demarrage__c</fullName>
    <inlineHelpText>Merci de renseigner le 1er jour du mois de la mensualité.</inlineHelpText>
    <label>Date de démarrage</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Cout_de_transport__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cout_de_transport__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brouillon</fullName>
                <default>true</default>
                <label>Brouillon</label>
            </value>
            <value>
                <fullName>En attente de validation</fullName>
            </value>
            <value>
                <fullName>Validé par la direction commerciale</fullName>
            </value>
            <value>
                <fullName>Rejeté par la direction commerciale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CoutTransportDao.cls
public inherited sharing class CoutTransportDao {

    public static List<Cout_de_transport__c> getCoutsByIds(List<Id> coutsId){
        return [Select Id, Name, Cout_mensuel_attendu_TTC__c, Date_de_demarrage__c, Date_de_fin__c 
                                        From Cout_de_transport__c
                                        Where Id in :coutsId];
    }
    
    public static List<Cout_de_transport__c> getAllCurrentCouts(){
        return [Select Id, Name, Cout_mensuel_attendu_TTC__c, Date_de_demarrage__c, Date_de_fin__c 
                From Cout_de_transport__c
                Where (CALENDAR_YEAR(Date_de_fin__c) >= :system.today().year() or Date_de_fin__c = null) and Statut__c = :CoutTransportService.STATUT_VALIDE];
    }
    
}