unpackaged/main/default/objects/Cout_de_transport__c/Cout_de_transport__c.object-meta.xml
<CustomObject>
    <label>Coût de transport</label>
    <nameField>
        <label>Nom du coût de transport</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coûts de transport</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cout_de_transport__c/fields/Cout_mensuel_attendu_TTC__c.field-meta.xml
<CustomField>
    <fullName>Cout_mensuel_attendu_TTC__c</fullName>
    <label>Coût mensuel attendu TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Cout_de_transport__c/fields/Date_de_demarrage__c.field-meta.xml
<CustomField>
    <fullName>Date_de_demarrage__c</fullName>
    <inlineHelpText>Merci de renseigner le 1er jour du mois de la mensualité.</inlineHelpText>
    <label>Date de démarrage</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Cout_de_transport__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Demande__c/Demande__c.object-meta.xml
<CustomObject>
    <label>Demande</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>N° de la demande</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demandes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Demande__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Demande__c/fields/Montant_forfait_mensuel_TTC__c.field-meta.xml
<CustomField>
    <fullName>Montant_forfait_mensuel_TTC__c</fullName>
    <label>Montant forfait mensuel TTC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Mensualite__c/Mensualite__c.object-meta.xml
<CustomObject>
    <label>Mensualité</label>
    <nameField>
        <label>Mensualité</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mensualités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mensualite__c/fields/Cout_de_transport__c.field-meta.xml
<CustomField>
    <fullName>Cout_de_transport__c</fullName>
    <label>Coût de transport</label>
    <referenceTo>Cout_de_transport__c</referenceTo>
    <relationshipLabel>Mensualités</relationshipLabel>
    <relationshipName>mensualites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CoutTransportServiceTest.cls
@isTest
private class CoutTransportServiceTest {

    @isTest
    static void updateFromDemandeTest(){
        Cout_de_transport__c coutTransportMensuel = DataFactoryTest.createCoutTransport('Forfait mensuel', 'Validé par la direction commerciale');
        coutTransportMensuel = [Select Id, Name/*, Mode_de_calcul_du_cout__c, Cout_journalier_semaine_TTC__c, Cout_journalier_samedi_TTC__c, Montant_forfait_mensuel_TTC__c*/, 
                         Cout_mensuel_attendu_TTC__c/*, Cout_moyen_mensuel__c*/, Date_de_demarrage__c, Date_de_fin__c 
                        From Cout_de_transport__c
                        Where Id = :coutTransportMensuel.Id];
        List<Mensualite__c> mensualites = MensualiteService.generateMensualites(coutTransportMensuel);
        insert mensualites;
        Demande__c demande = DataFactoryTest.createDemande(coutTransportMensuel.Id, 'Demande de modification d\'une facture');
        List<Demande__c> demandes = new List<Demande__c>();
        demandes.add(demande);
        Map<Id, Cout_de_transport__c> cdtsById = new Map<Id, Cout_de_transport__c>();
        cdtsById.put(coutTransportMensuel.Id, coutTransportMensuel);
        
        test.startTest();
        CoutTransportService.updateFromDemande(demandes, cdtsById);
        test.stopTest();
        
        coutTransportMensuel = [Select Id, Name/*, Mode_de_calcul_du_cout__c, Cout_journalier_semaine_TTC__c, Cout_journalier_samedi_TTC__c, Montant_forfait_mensuel_TTC__c*/, 
                         Cout_mensuel_attendu_TTC__c/*, Cout_moyen_mensuel__c*/, Date_de_demarrage__c, Date_de_fin__c 
                        From Cout_de_transport__c
                        Where Id = :coutTransportMensuel.Id];
        System.assert(coutTransportMensuel.Cout_mensuel_attendu_TTC__c == demande.Montant_forfait_mensuel_TTC__c);
    }
    
}