unpackaged/main/default/objects/Cout_de_transport__c/Cout_de_transport__c.object-meta.xml
<CustomObject>
    <label>Coût de transport</label>
    <nameField>
        <label>Nom du coût de transport</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coûts de transport</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cout_de_transport__c/fields/Cout_mensuel_attendu_TTC__c.field-meta.xml
<CustomField>
    <fullName>Cout_mensuel_attendu_TTC__c</fullName>
    <label>Coût mensuel attendu TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Cout_de_transport__c/fields/Date_de_demarrage__c.field-meta.xml
<CustomField>
    <fullName>Date_de_demarrage__c</fullName>
    <inlineHelpText>Merci de renseigner le 1er jour du mois de la mensualité.</inlineHelpText>
    <label>Date de démarrage</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Cout_de_transport__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cout_de_transport__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brouillon</fullName>
                <default>true</default>
                <label>Brouillon</label>
            </value>
            <value>
                <fullName>En attente de validation</fullName>
            </value>
            <value>
                <fullName>Validé par la direction commerciale</fullName>
            </value>
            <value>
                <fullName>Rejeté par la direction commerciale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Demande__c/Demande__c.object-meta.xml
<CustomObject>
    <label>Demande</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>N° de la demande</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demandes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Demande__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Demande__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nouvelle</fullName>
            </value>
            <value>
                <fullName>Envoyée à Biologistic</fullName>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>Répondu/en attente de validation</fullName>
            </value>
            <value>
                <fullName>Validée par Cerba</fullName>
            </value>
            <value>
                <fullName>Confirmée par Biologistic</fullName>
            </value>
            <value>
                <fullName>Abandonné</fullName>
                <label>Abandonnée</label>
            </value>
            <value>
                <fullName>En attente d&#39;approbation</fullName>
            </value>
            <value>
                <fullName>Validée par la direction commerciale</fullName>
            </value>
            <value>
                <fullName>Rejetée par la direction commerciale</fullName>
            </value>
            <value>
                <fullName>Ferme</fullName>
                <label>Fermé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mensualite__c/Mensualite__c.object-meta.xml
<CustomObject>
    <label>Mensualité</label>
    <nameField>
        <label>Mensualité</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mensualités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mensualite__c/fields/Cout_de_transport__c.field-meta.xml
<CustomField>
    <fullName>Cout_de_transport__c</fullName>
    <label>Coût de transport</label>
    <referenceTo>Cout_de_transport__c</referenceTo>
    <relationshipLabel>Mensualités</relationshipLabel>
    <relationshipName>mensualites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Mensualite__c/fields/Montant_provisionne_TTC__c.field-meta.xml
<CustomField>
    <fullName>Montant_provisionne_TTC__c</fullName>
    <label>Montant provisionné TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Mensualite__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VA</fullName>
                <label>Validée</label>
            </value>
            <value>
                <fullName>EL</fullName>
                <label>En litige</label>
            </value>
            <value>
                <fullName>NR</fullName>
                <default>true</default>
                <label>Facture non reçue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DemandeTriggerTest.cls
@isTest
private class DemandeTriggerTest {

    @isTest
    static void demandeTriggerTest(){
        Cout_de_transport__c coutTransport = DataFactoryTest.createCoutTransport('Forfait mensuel', 'Validé par la direction commerciale');
        coutTransport = [Select Id, Name,Cout_mensuel_attendu_TTC__c, Date_de_demarrage__c, Date_de_fin__c 
                        From Cout_de_transport__c
                        Where Id = :coutTransport.Id];
        List<Mensualite__c> mensualites = MensualiteService.generateMensualites(coutTransport);
        insert mensualites;
        Decimal montantOrigin = mensualites.get(0).Montant_provisionne_TTC__c;
        Demande__c demande1 = DataFactoryTest.createDemande(coutTransport.Id, 'Demande de modification d\'une facture');
        Demande__c demande2 = DataFactoryTest.createDemande(coutTransport.Id, 'Demande de suppression d\'une facture');
        
        test.startTest();
        
        demande1.Statut__c = 'Validée par la direction commerciale';
        update demande1;
        mensualites = [Select Montant_provisionne_TTC__c From Mensualite__c];
        coutTransport = [Select Id, Name, Cout_mensuel_attendu_TTC__c, Date_de_demarrage__c, Date_de_fin__c
                        From Cout_de_transport__c
                        Where Id = :coutTransport.Id];
        System.assert(mensualites.size() == (coutTransport.Date_de_demarrage__c.monthsBetween(coutTransport.Date_de_fin__c) + 1) 
                      && mensualites.get(0).Montant_provisionne_TTC__c == coutTransport.Cout_mensuel_attendu_TTC__c
                      && montantOrigin != mensualites.get(0).Montant_provisionne_TTC__c);
        
        demande2.Statut__c = 'Validée par la direction commerciale';
        update demande2;
        mensualites = [Select Montant_provisionne_TTC__c From Mensualite__c];
        System.assert(mensualites.size() == 0);
        
        test.stopTest();
    }
    
}